# This workflow will build a package using Maven and then create a release 

name: Maven Release

on:
  release:
    types: [created]
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'a-file-here.xml'
        xpath: '//version'

    - name: Publish to GitHub Releases
      uses: actions/create-release@1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.getxml.outputs.info }}
        release_name: ${{ steps.getxml.outputs.info }}
        draft: false
        prerelease: false
      
